name: Security audit
on:
  schedule:
    - cron: '0 * * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: arc-runner-set
    container: ${{ vars.RUNNER_IMAGE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
